export const AUTH_SET_AUTH_REQUEST = 'AUTH_SET_AUTH_REQUEST';
export const AUTH_SET_AUTH_SUCCESS_CORRECT = 'AUTH_SET_AUTH_SUCCESS_CORRECT';
export const AUTH_SET_AUTH_SUCCESS_INCORRECT = 'AUTH_SET_AUTH_SUCCESS_INCORRECT';
export const AUTH_SET_AUTH_USER_PHOTO = 'AUTH_SET_AUTH_USER_PHOTO';
export const AUTH_RESET_AUTH_DATA = 'AUTH_RESET_AUTH_DATA';
