export const SET_AUTH_REQUEST = 'SET_AUTH_REQUEST';
export const SET_AUTH_SUCCESS = 'SET_AUTH_SUCCESS';
export const SET_AUTH_FAILURE = 'SET_AUTH_FAILURE';
export const SET_AUTH_USER_PHOTO = 'SET_AUTH_USER_PHOTO';
export const RESET_AUTH_DATA = 'RESET_AUTH_DATA';
