export const SET_AUTH_REQUEST = 'SET_AUTH_REQUEST';
export const SET_AUTH_SUCCESS_CORRECT = 'SET_AUTH_SUCCESS_CORRECT';
export const SET_AUTH_SUCCESS_INCORRECT = 'SET_AUTH_SUCCESS_INCORRECT';
export const SET_AUTH_PHOTO = 'SET_AUTH_PHOTO';
export const RESET_AUTH_DATA = 'RESET_AUTH_DATA';
