export const SET_PROFILE_REQUEST = 'SET_PROFILE_REQUEST';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_STATUS_REQUEST = 'SET_PROFILE_STATUS_REQUEST';
export const SET_PROFILE_STATUS_SUCCESS = 'SET_PROFILE_STATUS_SUCCESS';
