export const PROFILE_SET_PROFILE_REQUEST = 'PROFILE_SET_PROFILE_REQUEST';
export const PROFILE_SET_PROFILE_SUCCESS = 'PROFILE_SET_PROFILE_SUCCESS';
export const PROFILE_SET_STATUS_REQUEST = 'PROFILE_SET_STATUS_REQUEST';
export const PROFILE_SET_STATUS_SUCCESS = 'PROFILE_SET_STATUS_SUCCESS';
