export const USERS_SET_USERS_REQUEST = 'USERS_SET_USERS_REQUEST';
export const USERS_SET_USERS_SUCCESS = 'USERS_SET_USERS_SUCCESS';
export const USERS_FOLLOW = 'USERS_FOLLOW';
export const USERS_UNFOLLOW = 'USERS_UNFOLLOW';
export const USERS_SET_PAGE = 'USERS_SET_PAGE';
export const USERS_SET_TOTAL_COUNT = 'USERS_SET_TOTAL_COUNT';
export const USERS_SET_SUBSCRIBERS_ID = 'USERS_SET_SUBSCRIBERS_ID';
