export const SET_USERS_REQUEST = 'SET_USERS_REQUEST';
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const SET_PAGE = 'SET_PAGE';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const SET_SUBSCRIBERS_ID = 'SET_SUBSCRIBERS_ID';
